### ISSUE TITLE
Make selection of group easier with auto-completion

### ISSUE THREAD

**Issue by lcarcone** [w3c/wbs-design#1]

**Comment by tripu** [comment]
Maybe we'll use [select2](https://github.com/select2/select2) for this.

**Comment by tripu** [comment]
Note to self: [MagicSuggest](https://github.com/nicolasbize/magicsuggest), [FlexSelect](https://github.com/rmm5t/jquery-flexselect).

**Comment by tripu** [comment]
@lcarcone, shall we consider this done, since you added [`html/index-site-select2.html`](https://w3c.github.io/wbs-design/html/index-site-select2.html)?

**Comment by tripu** [comment]
Done by @lcarcone.
