### ISSUE TITLE
not mobile friendly

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/wbs-design#11]
Hey guys!
- I checked the page but it's not responsive. and the Mobile Checker says there is no viewport declared. [mobile checker test here](https://validator.w3.org/mobile-alpha/?url=https%3A%2F%2Fw3c.github.io%2Fwbs-design%2Fhtml%2Fqtypes-site.html&profile=default)
- Be careful also on the page's width, which is too large on a mobile device (horizontal scroll) even if you declare a viewport.
  
  Very nice work though!

**Comment by tripu** [comment]
Done.
