### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by umairaziz112221** [w3c/wbs-design#119]
![Screenshot_2020-07-31-22-48-58](https://user-images.githubusercontent.com/63067048/90293552-ce43c100-de9d-11ea-93ce-2a14748618a9.png)

**Comment by lcarcone** [comment]
Which link is broken ?

**Comment by umairaziz112221** [comment]
P12 or pfx certificate

**Comment by tripu** [comment]
Spammy comment?
