### ISSUE TITLE
padding-right on #w3c_content_body

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/wbs-design#12]
Hey there is no padding on the right of the form and feels a bit awkward to me (not centered) is it on purpose?

**Comment by lcarcone** [comment]
Hi Guillaume,
I'll do a version with right padding to compare.
Thanks

**Comment by tripu** [comment]
Isn't that a consequence of the vertical gradient on the background?
It goes from dark blue on the top, to white on the bottom. I think that's why it looks like there's no padding on the top of the page (but looks OK if you scroll down one page or two).

**Comment by tripu** [comment]
Not an issue, I think, for the reasons explained.
