### ISSUE TITLE
Allow selecting multiple group sessions

### ISSUE THREAD

**Issue by zolkis** [w3c/wbs-design#121]
While registering to TPAC 2020, only one session could be selected as a group participant, though multiple groups could be selected as observer.

For members in multiple groups, it should be possible to register to sessions that are not in time conflict.
For instance, checkboxes, rather than radio buttons  could be used for selecting sessions.

**Comment by lcarcone** [comment]
@zolkis this is a known problem due to the registration tool used this year (see note 2 'Note for Group Meeting Registrants - Systems limitations'. We will use another registration form for the next meetings. Sorry for the inconvenience
