### ISSUE TITLE
Displaying large tables

### ISSUE THREAD

**Issue by lcarcone** [w3c/wbs-design#28]
Hi Tripu,

The results page [1] may contain large tables, like in the questions 13 and 15.
The default style used in the w3c template defines the css property 'overflow:hidden' for two parents of the page content (selectors '#w3c_main' and '.w3c_mainCol') so that the display of those tables is cut and no scrollbar is shown.
I made several tests to try go round this problem but I have not found a good solution.

Do you think there is a way to display the whole table in this case or should we try to use a specific structure/style for that page ?

Thank you

[1] https://w3c.github.io/wbs-design/html/qtypes-site-results.html

**Comment by tripu** [comment]
I'll shamelessly ping here CSS experts like @fantasai and @tabatkins to ask for a generic recipe for this.

The question is: how to force tables (or any other element, I guess) to either shrink to fit their container, or to solve their horizontal overflow with scroll bars.

It's not the first time I encounter this issue, and still I don't know a good solution :worried:

**Comment by tripu** [comment]
Fixed by @lcarcone in #34.
