### ISSUE TITLE
Restyle special templates

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#33]
* [ ] F2F meeting registration
* [x] Teleconference scheduling
* [x] Vote for transitioning to the new Patent Policy (see Switching to the W3C Patent Policy)
* [ ] Call For Review for Proposed Recommendations
* [ ] Call For Review for Working Group or Interest Group Charters

---

* Ask @dontcallmedom about XSLT in these?
* Find out if either of these is unused and thus can be discarded.

**Comment by tripu** [comment]
@lcarcone, any progress with this?

Let's chat and see how we can close [the current cycle](https://github.com/w3c/wbs-design/projects/1)!

**Comment by vivienlacourba** [comment]
tagging this as enhancement to indicate this is not of high priority as those pages are not used very often. Also looking at this last week with @lcarcone we saw some of those types could be deprecated, @lcarcone took an action to review their recent use and deprecate the unneeded ones from the WBS code.

**Comment by vivienlacourba** [comment]
"Vote for transitioning to the new Patent Policy (see Switching to the W3C Patent Policy)" has been deprecated.

**Comment by lcarcone** [comment]
I made some cosmetic changes in the remaining templates: I aligned les labels and replaced the static old footer with the new one.
