### ISSUE TITLE
Update footer of pages (?)

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#38]
Currently there is this notice at the bottom of pages:

> *Maintained by Laurent Carcone, from a development by <a href="/People/Dom/">Dominique Hazaël-Massieux</a> (<a href="mailto:dom@w3.org">dom@w3.org</a>) on an <a href="/2000/11/msm/">original design</a> by <a href="/People/cmsmcq/">Michael Sperberg-McQueen</a> <em>$Id: vote.php3,v 1.373 2017/08/16 19:56:22 antonio Exp $</em>. Please send bug reports and request for enhancements to <a href="mailto:lcarcone@w3.org">lcarcone@w3.org</a> with <a href="mailto:w3t-sys@w3.org">w3t-sys@w3.org</a> copied (if your mail client supports it, <a href="mailto:lcarcone@w3.org(Laurent%20Carcone),w3t-sys@w3.org(Systems Team)?subject=WBS%20bug%20report%20">send mail</a> directly to the right persons)*

Don't we want to update that? eg, relieving @lcarcone and the Systeam ML, and directing all feedback to  Sysreq instead.

**Comment by tguild** [comment]
Or better imho steer feedback here, to Github

**Comment by tripu** [comment]
I say we link to something like
[`https://github.com/w3c/wbs-design/issues/new?title=Bug%20/%20Feature%20request:%20[SHORT%20DESCRIPTION]&body=[DETAILED%20EXPLANATION]&labels=user-feedback`](https://github.com/w3c/wbs-design/issues/new?title=Bug%20/%20Feature%20request:%20[SHORT%20DESCRIPTION]&body=[DETAILED%20EXPLANATION]&labels=user-feedback) [works like an issue from a template; try it]
as preferred channel, and sysreq@ as fallback (because not everybody has a GitHub account).

@lcarcone, wdyt?
I'm assigning this one to you, as you're likely to be the one updating our WBS code.

**Comment by tguild** [comment]
Good point about not necessarily having a gh account. The template works for me, although I should have tested from a different browser not already logged into gh

**Comment by tripu** [comment]
If one is not already logged in on GH, the login page appears before the &ldquo;new issue&rdquo; form.
I think it's okay as you won't be able to do anything if you don't have an account, anyway.
