### ISSUE TITLE
Improve wide tables

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#41]
eg, reusing @bert-github's idea (collapsing individual columns when clicking their headings).

**Comment by deniak** [comment]
What doodle is doing with large table can also be an option, eg. https://doodle.com/poll/kzpuwakp85qzndib

**Comment by tripu** [comment]
Good idea, @deniak.

For what little I've seen, Doodle's tables aren't even `table`s, but a mess of nested `ul`s, `li`s and `div`s oriented horizontally, vertically, etc. Looking at the resources on the page, I haven't seen a specific CSS framework or JS library they're using for that.

It might be partly Backbone, it might be they're obfuscating some public tool(s), or it might be their own in-house recipe&hellip;

**Comment by tripu** [comment]
I'm implementing the &ldquo;explode table&rdquo; feature that I developed in this Codepen:
https://codepen.io/tripu/details/RyPGyZ/

**Comment by deniak** [comment]
Looks good! Is there a way to make the first N columns sticky so it's easier to see results for a specific person?

**Comment by lcarcone** [comment]
I don't think there is a css solution to have fixed header/columns for tables.
I did some research and I created a test page using the  'fixedheadertable' jquery plugin (see the table 'Details')
https://rawgit.com/w3c/wbs-design/table-header/html/table-header.html
Maybe we can use such a plugin in addition to the 'explode' feature.

**Comment by tripu** [comment]
Fixed in production (although not reflected in this repo; cf #68).
