### ISSUE TITLE
Results table: heading and values switched in some cases (?)

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#44]
Perhaps a bug in WBS code, not in the redesign.

to-do: find the example.

**Comment by lcarcone** [comment]
Indeed, there seems to be a problem in the display of the table 'Details' for question type 'Importance and Satisfaction Survey'.
see for instance https://www.w3.org/2002/09/wbs/102/wbs-improvement/results#xopinion or https://www.w3.org/2002/09/wbs/33280/web4business/results#xdasfdsag
There are very fews such questions in the WBS base.
I'm going to debug it

**Comment by tripu** [comment]
This is the only issue remaining in the current cycle of [WBS Design](https://github.com/w3c/wbs-design/projects/1). It would be good to close it so that we can plan a new &ldquo;sprint&rdquo; in the future. Did you find the issue, @lcarcone?

**Comment by lcarcone** [comment]
After several hours of debugging the WBS results code, I thing I fixed the problem.
This type of question is specific and some of its specificities had not been taken into account in the 'Details' table.
As I said, there are very fews instances of such a question in the DB.
I hope I hadn't introduce other bugs in the results.
