### ISSUE TITLE
Use the nav element

### ISSUE THREAD

**Issue by LJWatson** [w3c/wbs-design#48]
On the [WBS example](https://www.w3.org/2002/09/wbs/showwb), use the ```<nav>``` element to represent navigation blocks, and use the `aria-label` attribute to provide each navigation block with a unique accessible name. This will help screen reader users navigate and correctly identify the different navigation areas.

For example:
```
<nav aria-label="Views">
<ul class="secondary_nav">...</ul>
</nav>
```

```
<nav aria-label="Main">
<ul class="main_nav">...</ul>
</nav>
```

```
<nav aria-label="Breadcrumb">
<ul class="theme">...</ul>
</nav>
```

`Note:` do not use the word "navigation" inside the `aria-label`. Screen readers will automatically identify it as a navigation block based on the ```<nav>``` element itself (so will announce something like "Main navigation" for example).

**Comment by lcarcone** [comment]
Hello Léonie,

Thank you very much for your comments, we'll integrate them soon.

Regards,
Laurent

**Comment by lcarcone** [comment]
Hi Léonie,
We have added the 'nav' element to the WBS pages in production (https://www.w3.org/2002/09/wbs/ and others).
Could you tell us if it is ok for you ?

Best Regards

**Comment by tripu** [comment]
@LJWatson, OK to close this one now?
