### ISSUE TITLE
Why are these symbols so large?

### ISSUE THREAD

**Issue by edent** [w3c/wbs-design#50]
There's a big X and a Menu icon.  Even with my text-size set small, they're still larger than the text.

![screen shot 2018-01-23 at 16 27 19](https://user-images.githubusercontent.com/837136/35287517-68761e14-005a-11e8-8ce3-6511ea9e15cf.png)

May I suggest just regular text buttons ("ignore" and "see results").

Latest Chrome on Mac.

**Comment by lcarcone** [comment]
Hi,

I have the latest Chrome on Mac too but can't see this behavior.
Meanwhile I have reduced the icon, can you retry and let us know (maybe you will have to do a shift-reload)

Regards,
Laurent

**Comment by edent** [comment]
Yup - looks good now.

New redesign is excellent. Thanks!
