### ISSUE TITLE
Bug: "My Questionnaires" page does not display the user's name 

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/wbs-design#51]
On the [My Questionnaires](https://www.w3.org/2002/09/wbs/myQuestionnaires) page
It is written:
`This page shows questionnaires for `

This sentence seems to be missing the user's name at the end.

**Comment by lcarcone** [comment]
A couple of '<?' were not interpreted.
Note that this module (used for several pages: My questionnaires, All open Questionnaires, list of questionnaires for a group, ...) shows the status of the questionnaires and the group(s), not the user's name

**Comment by lcarcone** [comment]
I have removed the 'bug' label as I fixed the current problem (not related to new design but to the last php switch). 
I have added the 'enhancement' label as the user name has never been displayed in that page, and it needs a bit of work (multi-purpose page, label used elsewhere, for the title for example).

**Comment by vivienlacourba** [comment]
My comment was for the unfinished sentence not especially to display the user name. So you can close it.
