### ISSUE TITLE
Bug: Error message on https://www.w3.org/2002/09/wbs/myQuestionnaires

### ISSUE THREAD

**Issue by mweksler** [w3c/wbs-design#56]
On https://www.w3.org/2002/09/wbs/myQuestionnaires, I get the following error at the bottom of the page. The page seems to be functioning fine, but thought i'd point this out anyways

```
The following errors were encountered: Duplicate entry 'wpwg-pag-2017-83744-97592' for key 'PRIMARY'; cmd was INSERT INTO ignoredQuestionnaires (QaireNo,WGid,vorgid) VALUES ('wpwg-pag-2017',83744,97592)
```

**Comment by lcarcone** [comment]
Hi,
I guess you chose to ignore the questionnaire 'wpwg-pag-2017' then you made a reload of the resulting page (a browser warning should have been displayed).
I'll add a check to not do the update in that case.
Thanks,
Laurent

**Comment by lcarcone** [comment]
Hi,

I have added a check to prevent that case.

Thanks,
Laurent
