### ISSUE TITLE
Bug / Feature request: Make it obvious that submission succeeded

### ISSUE THREAD

**Issue by bert-github** [w3c/wbs-design#59]
The only indication that a form was successfully submitted is a single blue line that says: "Your 
answers have been successfully registered, thank you." Otherwise the page looks exactly as it looked before the form was submitted. That line is too easy to miss, especially if the title above it is a bit long.

I just had somebody who resorted to e-mail, because he thought the form reloaded without doing anything.

One solution may be to return a page that clearly indicates success and nothing else. It can maybe keep the top and left navigation menus, but it should not have the form.

**Comment by lcarcone** [comment]
Hi Bert,
I recently changed the title of the page when the form has been submitted, I have added the text ''Submitted reply for the survey ' before the name of the survey.
Do you think it is enough or do you think a clearer difference is needed ?

Thanks

**Comment by tripu** [comment]
@bert-github, WDYT now?

**Comment by lcarcone** [comment]
@bert-github 
I reused the W3C notifications colors to signal if a submission succeeded or not and in the case it succeeded, the form is not redisplayed, which I think is more obvious

**Comment by bert-github** [comment]
On Tuesday, October 16, 2018 5:13:31 AM CEST Laurent Carcone wrote:
> @bert-github
> I reused the W3C notifications colors to signal if a submission succeeded or
> not and in the case it succeeded, the form is not redisplayed, which I
> think is more obvious

Nice!



Bert
-- 
  Bert Bos                                ( W 3 C ) http://www.w3.org/
  http://www.w3.org/people/bos                               W3C/ERCIM
  bert@w3.org                             2004 Rt des Lucioles / BP 93
  +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France
