### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#6]
Compare the footer of [`w3c.github.io/wbs-design/html/qtypes-site.html`](https://w3c.github.io/wbs-design/html/qtypes-site.html) and that of [`w3.org/Consortium/siteindex.html`](http://www.w3.org/Consortium/siteindex.html).

The year in the copyright notice and the Twitter logo are different. There might be other changes.

(@lcarcone, I think it was @deniak who updated at least the Twitter image recently&hellip; maybe prompted by a request from @koalie?)

**Comment by deniak** [comment]
Good catch @tripu. We should now use the official twitter logo:

```
<img src="/2008/site/images/Twitter_bird_logo_2012.svg" alt="Twitter" height="40" class="social-icon" />
```

**Comment by lcarcone** [comment]
Fixed in branch laurent/2008-design
