### ISSUE TITLE
Enhancement: Fair padding throughout

### ISSUE THREAD

**Issue by koalie** [w3c/wbs-design#60]
I see a lot of space above certain elements that isn't available otherwise. This creates a yearning for space elsewhere (at least with me and @xueyuanjia who had to insert a few `<p><br></p>`). See for example the lack of space after ordered lists and blockquote in the May 2018 [AB election voting form](https://www.w3.org/2002/09/wbs/101147/ab20180502/).

**Comment by tripu** [comment]
Fixed by @lcarcone in #61.
