### ISSUE TITLE
Bug / Feature request: [SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by nikolaus1804a** [w3c/wbs-design#63]
[Report.txt](https://github.com/w3c/wbs-design/files/2127576/Report.txt)
[DETAILED EXPLANATION]

**Comment by nikolaus1804a** [comment]
# @dontcallmedom

**Comment by tripu** [comment]
@lcarcone, it didn't occur to me that adding this handy &ldquo;new issue&rdquo; hyperlink in WBS would cause *issue spam* like this&hellip;
I guess if this gets worse, we'll have to think how to deal with it or prevent it.
(I have just reported this specific issue.)
