### ISSUE TITLE
Make the “NOT registered” box more prominent

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#67]
A suggestion by @wseltzer (cf Sysreq no. 12747):

> *&ldquo;Can you make the warning much more prominent?
I filled out the [&hellip;] WBS and almost didn't wind up registered because the system didn't accept my form with a missing question, but the pale blue box almost didn't catch my attention with:&rdquo;*
>> &lsquo;Your answers have NOT been registered because of the following errors:
>> The question 'foo bar baz ' must be answered.&rsquo;

See a screenshot below.

Related to #59 (two sides of the same coin: it should be clear when submission succeeds, and it should be clear when it fails and why.)

![image](https://user-images.githubusercontent.com/1016538/44077876-52af3e54-9fa5-11e8-9b0e-8ba4c4317563.png)

**Comment by lcarcone** [comment]
Hi,
Currently there is no distinction in the messages displayed after a vote in WBS.
I'd propose to create 3 categories (error, warning, info) and to reuse the style defined in https://www.w3.org/2008/site/css/advanced for each of them (w3c_message.{error/warning/notice}).
If it is ok we'll work on it.

About the constraint on submission, there is an option for each question that defines whether a response is required or optional.

Thanks,
Laurent

**Comment by lcarcone** [comment]
@wseltzer 
I reused the W3C template colors/icons fot the submission of a survey, il will be more obvious to see if a submission succeeded or not (there will be a red message/icon in the last case).
When I have time, I will work on adding a link from each error message to the corresponding question.
