### ISSUE TITLE
Bug / Feature request: Incorrect date

### ISSUE THREAD

**Issue by twcook** [w3c/wbs-design#76]
In the questionnaire for:
APPLICATION FOR THE W3C WORKSHOP ON GRAPH DATA 4 - 6 MARCH 2019, BERLIN

In paragraph 10 the sentence "Invitations will be sent on or about August 24th." appears to have an incorrect date.

**Comment by lcarcone** [comment]
@twcook 
Hi,
I relayed the request to Dave Raggett who is in charge of this questionnaire.
Best Regards

**Comment by lcarcone** [comment]
@twcook 
Hi,
Dave Raggett changed the date in the questionnaire.
Thanks for the report.
Best Regards
