### ISSUE TITLE
Make submit button more visible

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/wbs-design#80]
Especially on mobile, the submit button is very hard to spot in the wash at the end of the page; I suggest using the conventional green or blue background button since that's the primary action button of the page.

**Comment by lcarcone** [comment]
Hi Dom,

What do you think of this style for buttons?
https://w3c.github.io/wbs-design/html/qtypes-site.html

Thanks

**Comment by dontcallmedom** [comment]
LGTM, thx!

**Comment by lcarcone** [comment]
Ok, I'll deploy it in the WBS code soon.
Thanks

**Comment by nigelmegitt** [comment]
The thin white text on the strongly coloured Submit button is quite hard to read on my screen - I'd suggest making the text a stronger weight.

**Comment by lcarcone** [comment]
Having vision problems make it difficult for me to distinguish characters thicker than 'normal'.
I'll do more tests with lighter background colors, higher font size and shorter value for the buttons, larger paddings.
Thanks for the feedback

**Comment by nigelmegitt** [comment]
No worries @lcarcone - to me this looked lighter than 'normal', even though I'm sure that's just a perception effect.

**Comment by dontcallmedom** [comment]
any news on deploying this?

**Comment by lcarcone** [comment]
@dontcallmedom I made some changes and displayed the 'remove' section a la github.
If it looks ok to you, I'll try to deploy that style next week (depending on my other tasks)

**Comment by lcarcone** [comment]
@dontcallmedom, are you ok with the last changes I made for this issue ?
https://w3c.github.io/wbs-design/html/qtypes-site.html
Thanks

**Comment by dontcallmedom** [comment]
LGTM, thx!
