### ISSUE TITLE
Add email to details table in compact view

### ISSUE THREAD

**Issue by tidoust** [w3c/wbs-design#82]
For cases where you want to export the results somewhere, typically when you organize workshops, WBS gives access to a compact view of the results that includes a pretty convenient "Details" table. It also features a link to retrieve the list of email addresses of the responders.

Could the email address of each responder appear next to the responder's name directly in the "Details" table?

**Comment by vivienlacourba** [comment]
+1 to add the email address to the result page unless if the results are public in which case email addresses should not be displayed.

**Comment by lcarcone** [comment]
@tidoust @vivienlacourba 
I have added the email address in the Details table for non public results pages.

Thanks

**Comment by tidoust** [comment]
Thanks @lcarcone ! And good idea to restrict this to non public results.
