### ISSUE TITLE
Feature request: id of creator and/or last updated

### ISSUE THREAD

**Issue by koalie** [w3c/wbs-design#88]
I wonder if it would be possible to add to each forms who created it and secondarily to indicate who and when it was last updated.

Then, if anyone has opinions whether it would be desirable NOT to do it, please, have at.

**Comment by lcarcone** [comment]
@koalie I'll add it when I'm done with my current tasks. Note that we don't keep the person who created a form, only the person who last modified it.

**Comment by vivienlacourba** [comment]
Discussing with @lcarcone in addition to knowing who created a questionnaire we will also store who created a given question.

The date of the creation/edit and who did it will be displayed on the questionnaire and question edit pages.

```
This questionnaire/question was created on YYYY-MM-DD by John Doe.
It was last updated on YYYY-MM-DD by Alan Smithee.
```

In addition, on the questionnaire edit page we will also display the date of the most recent updated question:
```
The most recently updated question is "Introduction" on YYYY-MM-DD by John Doe.
```

**Comment by lcarcone** [comment]
@koalie I have modified the edit page of the questionnaire to add the creation/modification infos of the questionnaire and the infos about the  last modified question.
Let me know if it is ok for you.

**Comment by koalie** [comment]
Thanks, Laurent.
Via the "edit" page is better than nothing. But what would make the most sense is if it were available in the "view" or "results" page.

**Comment by muffcrusher** [comment]
I am the one who created this mess lol I made this 2 years ago not knowing what i was doing and forgot about it till now

**Comment by vivienlacourba** [comment]
@koalie, I'm thinking that the info related to when and who created/updated a questionnaire is mostly of interest for the W3C Staff (based on our small experience of such requests in WBS), which is why @lcarcone and I thought to add it only on the edit pages.

I'm feeling that having it displayed to all users on the view and results page could unnecessarily complexify the UI.
What do you think?

**Comment by koalie** [comment]
You are probably right, @vivienlacourba and @lcarcone. I'm fine with this. Thanks again!
