### ISSUE TITLE
Bug in logging on to member area

### ISSUE THREAD

**Issue by kcoyle** [w3c/wbs-design#89]
When I tried logging on to https://www.w3.org/2002/09/wbs/99375/profile-def/ I am unable to get to the site unless the box is ticked for allowing non-W3C emails. Then I'm asked to login, and when I click on https://www.w3.org/2002/09/wbs/99375/profile-def/?login I do not connect to the login page. The same happens when I try to log into the member area from the Participate page. I do have W3C member access and am able to get on to, for example, the DXWG wiki, and my wiki page is https://www.w3.org/2017/dxwg/wiki/User:Kcoyle. My W3C email is kcoyle@kcoyle.net.

The symptom is that in the Firefox browser the tab for the site shows a moving ball that never stops moving. It also does not time out, and I accidently left it running all night, with no change. 

Some others have been able to access the poll site, but we aren't sure if anyone else is having this problem. If I find out I'll update this.

**Comment by lcarcone** [comment]
Hi,
We have not received such error reports for that questionnaire (nor for other questionnaires)
I see that all the responders of that questionnaire used their w3c account to reply.
Can you access the page https://www.w3.org/users/myprofile  with your credentials ?
Also have you tried with another browser or on another computer ?

Regards

**Comment by kcoyle** [comment]
Yes, thanks, oddly I am able to get on with Safari but not with Firefox. In Firefox I can't get to any member areas. Not a clue for the reason. I'll use Safari for W3C "business". Thanks.
